# -*- coding: utf-8 -*-
"""Chaithanya.D.S_expt7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jn6KlHrQpqzzRUDNY4A-FOy0HJgojq6m
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

cars_data = pd.read_csv("/content/archive.zip",index_col = 0, na_values = ['??','????'])

cars_data.info()

cars_data.dropna(axis=0,inplace=True)
cars_data

plt.scatter(cars_data['Age'],cars_data['Price'],c='red')
plt.title('Scatter plot of Price vs Age')
plt.xlabel('Age(month)')
plt.ylabel('Price(Euros)')
plt.show()

plt.hist(cars_data['KM'])

plt.hist(cars_data['KM'],color='green',edgecolor='white',bins=30)
plt.title('Histogram of KM')
plt.xlabel('Kilometeres')
plt.ylabel('Frequency')
plt.xticks(index,fueltype,rotation=60)
plt.show()

counts = [979,120,2]
fueltype = ('Petrol','Diesel','CNG')
index = np.arange(len(fueltype))

plt.bar(index,counts,color=['red','blue','cyan'])
plt.title('Bar plot of FuelType')
plt.xlabel('Fuel Type')
plt.ylabel('Frequency')
plt.xticks(index,fueltype,rotation=60)
plt.show()